jobs:
- job: Compilation
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      pip3 install --user black requests
      make lint
    displayName: 'Lint .py and .tex files'
  - script: |
      make setup_ubuntu
    displayName: 'Install system dependencies'
  - script: |
      # Make sure .git/refs/heads/master exists
      git checkout -b pr
      git checkout master
      git checkout pr

      make -j$(nproc) ebook
      cp controls-engineering-in-frc-ebook.pdf $(Build.ArtifactStagingDirectory)/controls-engineering-in-frc.pdf
    displayName: 'Generate PDF'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: controls-engineering-in-frc.pdf
