jobs:
- job: Compilation
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      pip3 install black
      ./format_code.py
    displayName: 'Run Python formatter'
  - script: |
      git --no-pager diff --exit-code HEAD  # Ensure formatter made no changes
    displayName: 'Check formatter output'
  - script: |
      make setup_ubuntu
    displayName: 'Install system dependencies'
  - script: |
      pip3 install --user black
    displayName: 'Install Python packages'
  - script: |
      # Make sure .git/refs/heads/master exists
      git checkout -b pr
      git checkout master
      git checkout pr

      make -j$(nproc) ebook
      cp controls-engineering-in-frc-ebook.pdf $(Build.ArtifactStagingDirectory)/controls-engineering-in-frc.pdf
    displayName: 'Generate PDF'
  - script: |
      # This check script is run after the book build so that any included .tex
      # files that are generated by the build exist.
      make lint
    displayName: 'Lint .tex files'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: controls-engineering-in-frc.pdf
