name: CI

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          python3 \
          python3-pip \
          python3-requests \
          python3-setuptools \
          python3-wheel
        # The Ubuntu 20.04 package is too old
        pip3 install --user black
    - name: Lint .py and .tex files
      run: make lint
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install system dependencies
      run: make setup_ubuntu
    - name: Generate PDF
      run: make -j$(nproc) ebook
    - uses: actions/upload-artifact@v2
      with:
        name: controls-engineering-in-frc.pdf
        path: controls-engineering-in-frc-ebook.pdf
